spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show_sql: true
    properties.hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop


spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
spring.jpa.properties.hibernate.dialect.storage_engine: innodb
# spring.datasource.hikari.jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
spring.h2.console.enabled: true # h2 메모리에서 실행, 직접 접근위해 웹 콘솔 옵션 활성화
spring.h2.console.settings.web-allow-others: true # 원격접속 허용